### PR TITLE
re #226 add code to support a GetConfigFiles command

### PR DESCRIPTION
**Pull request by adamrankin**

### CODE REVIEW

**Comment by adamrankin** [comment]
Kyle, Andras mentioned that you were looking into this feature. I'm starting to add some server side handling of commands relating to starting up a server.

**Comment by Sunderlandkyl** [comment]
Cool, I've implemented some other functions to receive commands, namely StartServer (allowing the config file to be passed as XML content), and StopServer.

The remote control server also sends commands to the session when PlusServer is started/stopped (ServerStarted/ServerStopped), and when messages are sent to the log.

I've got them connected to a C++ widget running in PlusRemote.

I had a discussion with Andras about how the synchronization of the list of config files between Slicer and Plus should be handled. It was decided that, at least for now, we were only going to allow the server to be started using config files that are stored in Slicer (in vtkMRMLTextNode). I think that it would be useful at some point to support both, making the distinction between local and remote config files.

What other commands have you started implementing?

**Comment by Sunderlandkyl** [comment]
Also, I think at least one other command that I would like to implement would be a GetServerStatus/GetServerInfo command, to retrieve information on the currently running server (isRunning, config file, log level, PlusOpenIGTLinkServer ports, etc.).

**Comment by adamrankin** [comment]
With regards to config files, I don't think Slicer should store any (except in memory). The server should be the master list, and clients should query for the list of available config files (very cheap request, can send every 1 minute if you want behaviour like that).

I've just implemented the PlusServerLauncher handling the command "GetConfigFiles" which I haven't added to PlusLib yet. It returns the list of files and the separator used in the metadata.

Other than that, great. The StartServer command could also take a filename as a parameter, instead of XML contents.

**Comment by adamrankin** [comment]
Do you have a branch available for me to look at?

**Comment by Sunderlandkyl** [comment]
Yes, branch is here: https://github.com/Sunderlandkyl/PlusApp/tree/remote-control
Fair warning, this has been an OpenIGTLink learning experience for me, so most of my OpenIGTLink code is probably buggy.

I did have the option to specify file name in an earlier version, so I think that's a good idea.

I believe that the justification for not using the config file from Plus was that Slicer could be controlling several different PlusServerLaunchers, and that it made sense to keep the config files in Slicer so that the user would not have to worry about adding the required config files to each, they could just keep them organized in one location, and control their use/distribution through slicer.

Maybe some sort of middle ground could be an AddConfigFile command that sends a config file to PlusServerLauncher and writes it to the config file directory. It could then be used to start the server.

**Comment by adamrankin** [comment]
No problem, this has been an igtlio learning experience for me, it's very strangely designed.

I understand the justification, but I don't agree. Each server knows what physical devices are attached to it and will provide config files appropriate to those devices (eventually we could have dynamic querying and building, but that's long in the future). In my mind, Slicer is passive and can only connect to what the server provides.

From the user perspective, we can make it seamless in that when they choose a different server, the list for that server simply shows up.

The user would not be responsible for populating a server with config files, the server operator would respond to user's needs.

AddConfigFile sounds like a reasonable idea, except how does Slicer know what config files the server will be able to run?

**Comment by Sunderlandkyl** [comment]
I hadn't considered only showing config files for the physically connected devices.

In that case, AddConfigFile could be used to send the config file, regardless of if it was supported. This could be followed up by a GetConfigFiles command, which would include the newly added config file, if it was supported.

**Comment by adamrankin** [comment]
Hmm, determining if a config file is supported is usually done by running, which then throws an error if it can't connect.

Determining support from config file only would be a fair bit of coding, with lots of changing rules. If we really want to let clients add config files, it's up to them as to whether they will work on the server or not.

**Comment by Sunderlandkyl** [comment]
Sorry, when you said:
>Each server knows what physical devices are attached to it 

I misunderstood your meaning. I thought that you meant that the GetConfigFiles would only return config files for the connected devices. I realize now that you meant that the servers are set up to only include config files for the connected devices.

I agree then that it's impossible for Slicer to know what devices are supported when using AddConfigFile.

**Comment by lassoan** [comment]
We've talked about this extensively and the conclusion was that we have multiple valid use cases - depending on what environment you are working, how equipment is shared, and who and how sets up experiments or clinical systems.

It seems that in the PerkLab for most of our projects it is preferable _not_ to store configurations on servers, but manage everything on Slicer side. Therefore, we work on this approach now.

I agree that it makes perfect sense to have the option for storing config files on the server side. That would have been my first choice, too, but this was not what users wanted here.

We'll keep working and refining the local config file based workflow. It would be nice if @adamrankin could work on the remote config file based workflow - just coordinate with @Sunderlandkyl to minimize commit conflicts and figure out how the GUI in Slicer should look like. I think there will be no design conflicts, you'll just add commands for getting/setting/modifying config files and both approaches will be available from the GUI.

**Comment by Sunderlandkyl** [comment]
For reference, this is the current version of my widget implementation: https://github.com/Sunderlandkyl/SlicerOpenIGTLink/tree/plus-remote-widget

**Comment by adamrankin** [comment]
@lassoan Ok, makes sense. I'll scan Kyle's branch to see what he's implemented in Plus, and then finish the rest.

Do we want to allow modifying config files? That seems dangerous, especially if they break one, then it's broken for all users? Add only?

**Comment by lassoan** [comment]
These are good questions. Ability to add new without edit/remove would probably result in many random config files.

I would choose options that are the easiest to implement and improve based on user demand.

**Comment by adamrankin** [comment]
@Sunderlandkyl I've added the PlusServerLauncher code, and started writing code/GUI to add metadata sending/receiving in OpenIGTLinkRemote.

That turned into a rabbit hole. Let me know where you are in Slicer land, and maybe you can integrate my code into yours.

**Comment by Sunderlandkyl** [comment]
I see that, I'm working on integrating my slicer code with your PlusApp changes.

Question, are you currently able to send commands to the remote control server?
The command are not received for me unless I add a multi-threaded function calling m_RemoteControlServerLogic::PeriodicProcess().

**Comment by adamrankin** [comment]
I added that to PlusServerLauncher, yes.

For me Slicer is not sending commands properly.

**Comment by adamrankin** [comment]
Oops, forgot to commit that.

**Comment by Sunderlandkyl** [comment]
Yes, OpenIGTLink Remote hasn't worked since OpenIGTLinkIF was moved into SlicerOpenIGTLink.

**Comment by Sunderlandkyl** [comment]
My code for remote starting stopping the server is in PlusRemote.

**Comment by adamrankin** [comment]
Ok, changes commited. Will test with PlusRemote

**Comment by lassoan** [comment]
> The command are not received for me unless I add a multi-threaded function calling m_RemoteControlServerLogic::PeriodicProcess().

I don't fully understand this. If PeriodicProcess can be called from any thread then a background thread should be created internally. If PeriodicProcess must be called from the main thread (this is more likely) then it should be called from directly from the message loop of the application or using a timer (and not by creating a new thread).

**Comment by adamrankin** [comment]
PeriodicProcess must be called from the main thread. I do this via QTimer

**Comment by Sunderlandkyl** [comment]
@adamrankin How are you sending the commands? I still can't get my commands to be recognized, specifically because I find that the CommandReceivedEvent is received by igtlio::Logic, not igtlio::Device, here: https://github.com/PlusToolkit/PlusApp/blob/d1a03107ceb1512e241ff7fbfc31cb2e58b1d684/PlusServerLauncher/PlusServerLauncherMainWindow.cxx#L582-L586

**Comment by adamrankin** [comment]
I haven't tested yet. I haven't yet been able to successfully send a command, let alone receive. I am very tempted to re-write igtlio to expose SendData to be public. This whole device infrastructure is nuts.

**Comment by Sunderlandkyl** [comment]
Ok, sounds good, I'll make some changes then to see if I can get it working.

**Comment by lassoan** [comment]
> I haven't tested yet. I haven't yet been able to successfully send a command, let alone receive. I am very tempted to re-write igtlio to expose SendData to be public. 

The API is already pretty simple - a single line per command:

    igtlio::CommandDevicePointer clientDevice = client.Session->SendCommandQuery("TestDevice_Command", "GetDeviceParameters", "<Command> <Parameter Name=\"Depth\" /> </Command>", igtlio::ASYNCHRONOUS);

    igtlio::CommandDevicePointer serverDevice = server.Session->SendCommandResponse(clientDevice->GetDeviceName(), "GetDeviceParameters", "<Command> <Result>GetDeviceParameters: success</Result> <Parameter Name=\"Depth\" Value=\"45\" /></Command>");

However, I agree that using "device" to track command status is not good and instead command processing should be independent from devices. The main reason is that a device represents latest state of a physical or virtual device, while commands represents events. I think command processing implementation is already quite independent, so maybe it is just not reflected in the API.

**Comment by adamrankin** [comment]
`igtlio::CommandDevicePointer clientDevice = client.Session->SendCommandQuery("TestDevice_Command", "GetDeviceParameters", "<Command> <Parameter Name=\"Depth\" /> </Command>", igtlio::ASYNCHRONOUS);`

Is this what OpenIGTLinkRemote does? Because if so, it doesn't work. It spits out an error about message failure or something.

**Comment by adamrankin** [comment]
The API may be simple, but it is not clear. Is a session mandatory? How does one recover a session from a device object? From a connector? etc...

The use flow of igtlio is not clear.

**Comment by adamrankin** [comment]
`Sending OpenIGTLinkMessage: STRING/ACK_1, message not available from device`

Error message when trying to send:
`<Command Name="GetConfigFiles"/>`

**Comment by adamrankin** [comment]
@Sunderlandkyl How do you use PlusRemote to send commands? I don't see a command box in the UI

**Comment by lassoan** [comment]
This is one of the tests in OpenIGTLinkIO\Testing. It used to work.

> Is a session mandatory? How does one recover a session from a device object? From a connector?

Session is the high-level API, see OpenIGTLinkIO tests. If you need the connector then you can get it from the session.

    session = Logic->ConnectToServer("localhost", -1, igtlio::ASYNCHRONOUS);
    connector = session->GetConnector();

**Comment by adamrankin** [comment]
In Slicer, how can I get the session?

Is there one session per vtkMRMLIGTLConnectorNode? (no, there is an igtlio::Connector per connectornode)

Can you get the session from a connector? (no)

The SendCommand function on a connector is hardcoded to v1 style query.

SendMessage requires a DeviceKeyType, is this linked to IGTL message types?

I suspect we should simply re-write the command part of the API to be more clear. It would seem in Slicer that we do not have access to a igtlio::Session. I will keep looking.

**Comment by Sunderlandkyl** [comment]
@adamrankin my branch is at https://github.com/Sunderlandkyl/SlicerOpenIGTLink/tree/plus-remote-widget

At the OpenIGTLinkIF level, there is a helper class called vtkSlicerOpenIGTLinkCommand that can be used to store command information.

Then you can call vtkMRMLIGTLConnectorNode::SendCommand(vtkSlicerOpenIGTLinkCommand* command).

There is a class called vtkSlicerOpenIGTLinkCommand in SlicerOpenIGTLink that simlifies the command sending and receiving somewhat.

**Comment by adamrankin** [comment]
@Sunderlandkyl Yes, this is what OpenIGTLink Remote is using now, and it doesn't work.

I am deep into qSlicerOpenIGTLinkRemoteCommandWidget, vtkSlicerOpenIGTLinkRemoteLogic, vtkMRMLIGTLConnectorNode, and igtlio::Connector.

Command sending fails in igtlio::Connector line 905

**Comment by adamrankin** [comment]
ok, DeviceKeyType is something like

```
DeviceKeyType
{
std::string type = "COMMAND"
std::string name = "GetConfigFiles"
}
```

**Comment by lassoan** [comment]
Session interface is useful because it can handle (maybe not yet but in the future) multiple connections. It is nice if you don't need to manage connectors manually and it easier to set up a observers to a single session object than for each connection object. Probably OpenIGTLink client in Slicer should use the session API.

**Comment by Sunderlandkyl** [comment]
@adamrankin Just checking, but are you using https://github.com/openigtlink/SlicerOpenIGTLink or https://github.com/openigtlink/OpenIGTLinkIF?

**Comment by adamrankin** [comment]
https://github.com/openigtlink/SlicerOpenIGTLink

**Comment by adamrankin** [comment]
Ok, enough of this. Switched to your fork. @Sunderlandkyl Do I use plus-widget-working?

I will try to integrate my metadata UI into your fork.

**Pull request merged**
