### PR TITLE
Enabling doxygen XML output option in anticipation of doxygen markdow…

### PR DESCRIPTION
**Pull request by adamrankin**
…n output

### CODE REVIEW

**Comment by lassoan** [comment]
I would keep API documentation in Qt comment format (that is replicated by doxygen).
For user manual we can go to more limited markups (Markdown, RTD, ...) but then I would switch the generator from doxygen to Sphinx.

**Comment by adamrankin** [comment]
Oh yes, this isn't the comment format, this is the output format.

**Comment by adamrankin** [comment]
It looks like Sphinx doesn't generate markdown either.

**Comment by lassoan** [comment]
Sphinx primarily uses `restructured text` (rst) as input but can configured to take markdown (md) as well.

**Pull request merged**
