### PR TITLE
ENH: Enabling support for VS2019 and VTK >= 8.9

### PR DESCRIPTION
**Pull request by adamrankin**
Packaging of VTK currently not working

### CODE REVIEW

**Comment by adamrankin** [comment]
Works as expected with 8.2

VTK 9 breaks a number of things, and forces the migration to QVTKOpenGLNativeWidget, which at first pass doesn't work correctly.

Do we want to continue supporting fCal?

@Sunderlandkyl @lassoan

**Comment by lassoan** [comment]
> VTK 9 no longer accepts CMAKE_RUNTIME_OUTPUT_DIRECTORY (and similar) 

You can ask Ben Boeckel on the VTK forum. He usually responds very quickly to questions related to the new VTK build system.

> QVTKOpenGLNativeWidget, which at first pass doesn't work correctly.

QVTKOpenGLNativeWidget is a drop-in replacement, it should work well (although in Slicer we experience an issue that images don't appear in slice views).. What does not work correctly?

We invested several years into developing a complete freehand calibration system, which works quite well and we should keep alive. We could probably reimplement it in Slicer, but that would be significant effort. Also, fCal also serves as the only complete example of how Plus can be used in Qt applications. So, we should make it work.

**Comment by adamrankin** [comment]
> What does not work correctly?
The slice view does not update. The only way to see the slice is to switch to another toolbox and switch back

**Comment by lassoan** [comment]
There may be some bug in VTK that interferes with image display. We are working on fixing it in Slicer and will see if it is applicable to fCal, too.

**Comment by adamrankin** [comment]
Ok, I'll do some digging to see if I can find the cause.

**Comment by adamrankin** [comment]
Problem line here:
https://github.com/Kitware/VTK/blob/master/GUISupport/Qt/QVTKRenderWindowAdapter.cxx#L248

this->DoVTKRenderInPaintGL never reset to true unless widget is resized or `activateBuffers` is called.

**Comment by adamrankin** [comment]
Perhaps this is intended. Workaround/solution is to call render yourself.

**Comment by adamrankin** [comment]
Mostly repaired. The only thing that isn't quite right is that the segmentation parameter dialog doesn't render unless you resize it. Investingating

**Comment by adamrankin** [comment]
Seg param dialog image view not rendering unless resized
VTK packaging not working (part of not accepting CMAKE_RUNTIME_OUTPUT_DIRECTORY?)

**Comment by adamrankin** [comment]
Separated out the QVTKWidget migration so that I can move to VTK 9 in phases

**Pull request merged**
