### PR TITLE
[Bug] Error packaging without PLUSBUILD_DOWNLOAD_PlusDATA

### PR DESCRIPTION
**Pull request by jamesobutler**
I'm unable to successfully package PlusApp if I unchecked "PLUSBBUILD_DOWNLOAD_PlusData" when I originally configured the cmake for PlusBuild.  I was able to successfully package PlusApp when I commented out the following lines in the InstallFiles.cmake file.  I'll let someone else address how they want to handle this bug rather than just commenting out code.

This was the original package error:
[PACKAGE fail.txt](https://github.com/PlusToolkit/PlusApp/files/1002359/PACKAGE.fail.txt)

### CODE REVIEW

**Comment by adamrankin** [comment]
Hmm, at the moment this is by design. The base package of Plus includes sample config files (and other items from PlusData). I'm open to discussing if package should not include any data related files.

What is your use case for packaging without ROM files, config files, etc...?

I don't think commenting out the includes is the correct solution. You could add some CMake logic to check to see if PLUSBUILD_DOWNLOAD_PlusData is enabled when packaging (by passing it through to PlusApp from PlusBuild).

**Comment by adamrankin** [comment]
Also, please run Utilities/SetupForDevelopment.sh in your PlusApp/PlusLib/PlusBuild folders. We require commits to reference a specific ticket managed [here](https://app.assembla.com/spaces/plus/tickets/realtime_list)

**Comment by jamesobutler** [comment]
I'm just trying to build and package a lighter PlusApp that only includes support for using an MMF_video device. I've also been trying to install the plus app within "C:/program files/" instead of a user directory, but it continues to give me install errors.

**Comment by adamrankin** [comment]
Ok, sounds reasonable.

With regards to Program Files installs, you'll need to run it as an administrator. We currently have it configured to default to user space. Again, something worth discussing.

**Comment by jamesobutler** [comment]
Ok, manually forcing it to run the installer as an administrator works.  Being given the option to install to a unique directory even though the installer wasn't being run as administrator was throwing me off.

**Comment by adamrankin** [comment]
There's probably a CMake-NSIS option to request Administrator during the install (as we're all used to with most installers) if you choose an Admin only folder. Up to @lassoan if we want to make our NSIS install fancier.

**Comment by jamesobutler** [comment]
Ok. Well regarding the lighter PlusApp I can include the mmf config files and remove everything else manually.  You can disregard the request to allow packaging without having downloaded PlusData.

**Comment by adamrankin** [comment]
See https://app.assembla.com/spaces/plus/tickets/1197-enable-optional-inclusion-of-data-files-in-plus-install/details for fix.

**Comment by lassoan** [comment]
Ability to install without admin access is a feature (a la Google Chrome), but you can make admin access required (you should be able to find it in the change log; but if you can't find it and you need it then let me know).

If you need really small footprint then probably you are better off with a custom PlusBuild project where you remove Qt and all other device support that you don't need, minimize VTK, ITK, etc. components, and do a static build of PlusServer.exe. You then get a single executable that you can just run anywhere.

**Comment by jamesobutler** [comment]
Ok, I'll definitely consider that. Thanks

**Pull request closed without merging**
